language: cpp
sh: &sh
  - ./build/cs -v
  - ./build/cs -h
  - ./build/cs_dbg -h
  - ./build/cs_repl -v
  - ./build/cs_repl -h
  - ./build/cs examples/benchmark.csc
  - ./build/cs -i build tests/extension.csc
  - ./build/test-covscript tests/function_invoker.csc
bat: &bat
  - build\cs -v
  - build\cs -h
  - build\cs_dbg -h
  - build\cs_repl -v
  - build\cs_repl -h
  - build\cs examples\benchmark.csc
  - build\cs -i build tests\extension.csc
  - build\test-covscript tests\function_invoker.csc
jobs:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
      install:
        - mkdir build
        - cd build
        - cmake -G "Unix Makefiles" ..
        - cmake --build . -- -j4
        - cd ..
      script: *sh
    - os: linux
      dist: xenial
      compiler: clang
      install:
        - mkdir build
        - cd build
        - cmake -G "Unix Makefiles" ..
        - cmake --build . -- -j4
        - cd ..
      script: *sh
    - os: osx
      osx_image: xcode10
      install:
        - mkdir build
        - cd build
        - cmake -G "Unix Makefiles" ..
        - cmake --build . -- -j4
        - cd ..
      script: *sh
    - os: windows
      install:
        - powershell
        - mkdir build
        - cd build
        - cmake -G "Visual Studio 15 2017" ..
        - cmake --build . --config MinSizeRel
        - cd ..
      script: *bat