language: cpp
jobs:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
      install:
        - mkdir build
        - cd build
        - cmake -G "Unix Makefiles" ..
        - cmake --build . -- -j8
        - cp -r ../include .
        - mkdir lib
        - cp *.a ./lib
        - cd ..
    - os: linux
      dist: xenial
      compiler: clang
      install:
        - mkdir build
        - cd build
        - cmake -G "Unix Makefiles" ..
        - cmake --build . -- -j8
        - cp -r ../include .
        - mkdir lib
        - cp *.a ./lib
        - cd ..
    - os: osx
      osx_image: xcode10
      install:
        - mkdir build
        - cd build
        - cmake -G "Unix Makefiles" ..
        - cmake --build . -- -j8
        - cp -r ../include .
        - mkdir lib
        - cp *.a ./lib
        - cd ..
    - os: windows
      install:
        - mkdir build
        - cd build
        - cmake -G "Visual Studio 15 2017 Win64" ..
        - cmake --build . --config MinSizeRel
        - cp ./MinSizeRel/* .
        - cp -r ../include .
        - mkdir lib
        - cp *.lib ./lib
        - cd ..
script:
  - ./build/cs -v
  - ./build/cs -h
  - ./build/cs_dbg -v
  - ./build/cs_dbg -h
  - ./build/cs examples/benchmark.csc
  - ./build/cs -i build tests/extension.csc
  - ./build/test-covscript tests/function_invoker.csc
  - export CS_DEV_PATH="$(echo 'runtime.get_current_dir()' | ./build/cs_repl -s)"/build
  - cd tests
  - ../build/cs -i ../examples ../examples/csbuild.csc check
  - ../build/cs -i ../examples ../examples/csbuild.csc generate
  - ../build/cs -i ../examples ../examples/csbuild.csc make
  - ../build/cs -i gen/build extension.csc