language: cpp
jobs:
  include:
    - os: linux
      dist: xenial
      compiler:
        - gcc
        - clang
      install:
        - bash ./csbuild/make.sh
    - os: osx
      osx_image: xcode10
      install:
        - bash ./csbuild/make.sh
    - os: windows
      install:
        - csbuild\make.bat