os:
  - osx
  - linux
  - windows
compiler:
  - clang
  - gcc
dist: xenial
language: cpp
osx_image: xcode10
matrix:
  include:
    - os: osx
      install: bash csbuild/make.sh
    - os: linux
      install: bash csbuild/make.sh
    - os: windows
      install: bash csbuild/make.bat
script:
  - ./build/cs -v
  - ./build/cs -h
  - ./build/cs_dbg -v
  - ./build/cs_dbg -h
  - ./build/cs_repl -v
  - ./build/cs_repl -h
  - ./build/cs ./examples/benchmark.csc