name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on:
    - windows-latest
    - ubuntu-latest
    - macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
