name: schedule

on:
  schedule:
    - cron:  '0 */2 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - name: build-ubuntu
        if: matrix.os == 'ubuntu-latest'
        run:
          - git clone https://github.com/covscript/csbuild
          - cd csbuild/deb_tools
          - bash auto-build.sh
      
      - name: build-macos
        if: matrix.os == 'macOS-latest'
        run:
          - git clone https://github.com/covscript/csbuild
          - cd csbuild/mac_tools
          - bash auto-build.sh

      - uses: actions/upload-artifact@master
        if: matrix.os == 'ubuntu-latest'
        with:
          name: covscript-ubuntu
          path: csbuild/deb_tools/deb-src/*.deb

      - uses: actions/upload-artifact@master
        if: matrix.os == 'macOS-latest'
        with:
          name: covscript-macos
          path: csbuild/mac_tools/*.dmg